// AUTO-GENERATED by scripts/sync.ts — do not edit manually.
// Run `npm run sync` after adding or removing a rule.
import type { RuleFunction, RuleMeta } from '../types';
import { browserApiInUseEffect, meta as browserApiInUseEffectMeta } from './browser-api-in-useeffect';
import { catchMustLogToSentry, meta as catchMustLogToSentryMeta } from './catch-must-log-to-sentry';
import { expoFontLoadedCheck, meta as expoFontLoadedCheckMeta } from './expo-font-loaded-check';
import { expoImageImport, meta as expoImageImportMeta } from './expo-image-import';
import { fetchResponseOkCheck, meta as fetchResponseOkCheckMeta } from './fetch-response-ok-check';
import { glassInteractiveProp, meta as glassInteractivePropMeta } from './glass-interactive-prop';
import { glassNeedsFallback, meta as glassNeedsFallbackMeta } from './glass-needs-fallback';
import { glassNoOpacityAnimation, meta as glassNoOpacityAnimationMeta } from './glass-no-opacity-animation';
import { headerShownFalse, meta as headerShownFalseMeta } from './header-shown-false';
import { loggerErrorWithErr, meta as loggerErrorWithErrMeta } from './logger-error-with-err';
import { nativeTabsBottomPadding, meta as nativeTabsBottomPaddingMeta } from './native-tabs-bottom-padding';
import { noBorderWidthOnGlass, meta as noBorderWidthOnGlassMeta } from './no-border-width-on-glass';
import { noClassComponents, meta as noClassComponentsMeta } from './no-class-components';
import { noComplexJsxExpressions, meta as noComplexJsxExpressionsMeta } from './no-complex-jsx-expressions';
import { noEmojiIcons, meta as noEmojiIconsMeta } from './no-emoji-icons';
import { noInlineScriptCode, meta as noInlineScriptCodeMeta } from './no-inline-script-code';
import { noInlineStyles, meta as noInlineStylesMeta } from './no-inline-styles';
import { noLooseEquality, meta as noLooseEqualityMeta } from './no-loose-equality';
import { noMagicEnvStrings, meta as noMagicEnvStringsMeta } from './no-magic-env-strings';
import { noManualRetryLoop, meta as noManualRetryLoopMeta } from './no-manual-retry-loop';
import { noNestedTryCatch, meta as noNestedTryCatchMeta } from './no-nested-try-catch';
import { noOptionalProps, meta as noOptionalPropsMeta } from './no-optional-props';
import { noReactQueryMissing, meta as noReactQueryMissingMeta } from './no-react-query-missing';
import { noRelativePaths, meta as noRelativePathsMeta } from './no-relative-paths';
import { noRequireStatements, meta as noRequireStatementsMeta } from './no-require-statements';
import { noResponseJsonLowercase, meta as noResponseJsonLowercaseMeta } from './no-response-json-lowercase';
import { noSafeAreaView, meta as noSafeAreaViewMeta } from './no-safeareaview';
import { noServerImportInClient, meta as noServerImportInClientMeta } from './no-server-import-in-client';
import { noSilentSkip, meta as noSilentSkipMeta } from './no-silent-skip';
import { noStringCoerceError, meta as noStringCoerceErrorMeta } from './no-string-coerce-error';
import { noStylesheetCreate, meta as noStylesheetCreateMeta } from './no-stylesheet-create';
import { noSyncFs, meta as noSyncFsMeta } from './no-sync-fs';
import { noTabBarHeight, meta as noTabBarHeightMeta } from './no-tab-bar-height';
import { noTailwindAnimationClasses, meta as noTailwindAnimationClassesMeta } from './no-tailwind-animation-classes';
import { noTypeAssertion, meta as noTypeAssertionMeta } from './no-type-assertion';
import { preferGuardClauses, meta as preferGuardClausesMeta } from './prefer-guard-clauses';
import { preferLucideIcons, meta as preferLucideIconsMeta } from './prefer-lucide-icons';
import { preferNamedParams, meta as preferNamedParamsMeta } from './prefer-named-params';
import { requireUseClient, meta as requireUseClientMeta } from './require-use-client';
import { safeJsonParse, meta as safeJsonParseMeta } from './safe-json-parse';
import { scrollviewHorizontalFlexgrow, meta as scrollviewHorizontalFlexgrowMeta } from './scrollview-horizontal-flexgrow';
import { sqlNoNestedCalls, meta as sqlNoNestedCallsMeta } from './sql-no-nested-calls';
import { tabsScreenOptionsHeaderShown, meta as tabsScreenOptionsHeaderShownMeta } from './tabs-screen-options-header-shown';
import { textInputKeyboardAvoiding, meta as textInputKeyboardAvoidingMeta } from './textinput-keyboard-avoiding';
import { transitionGestureScrollview, meta as transitionGestureScrollviewMeta } from './transition-gesture-scrollview';
import { transitionPreferBlankStack, meta as transitionPreferBlankStackMeta } from './transition-prefer-blank-stack';
import { transitionProgressRange, meta as transitionProgressRangeMeta } from './transition-progress-range';
import { transitionSharedTagMismatch, meta as transitionSharedTagMismatchMeta } from './transition-shared-tag-mismatch';
import { transitionWorkletDirective, meta as transitionWorkletDirectiveMeta } from './transition-worklet-directive';
import { urlParamsMustEncode, meta as urlParamsMustEncodeMeta } from './url-params-must-encode';

export const rules: Record<string, RuleFunction> = {
  'browser-api-in-useeffect': browserApiInUseEffect,
  'catch-must-log-to-sentry': catchMustLogToSentry,
  'expo-font-loaded-check': expoFontLoadedCheck,
  'expo-image-import': expoImageImport,
  'fetch-response-ok-check': fetchResponseOkCheck,
  'glass-interactive-prop': glassInteractiveProp,
  'glass-needs-fallback': glassNeedsFallback,
  'glass-no-opacity-animation': glassNoOpacityAnimation,
  'header-shown-false': headerShownFalse,
  'logger-error-with-err': loggerErrorWithErr,
  'native-tabs-bottom-padding': nativeTabsBottomPadding,
  'no-border-width-on-glass': noBorderWidthOnGlass,
  'no-class-components': noClassComponents,
  'no-complex-jsx-expressions': noComplexJsxExpressions,
  'no-emoji-icons': noEmojiIcons,
  'no-inline-script-code': noInlineScriptCode,
  'no-inline-styles': noInlineStyles,
  'no-loose-equality': noLooseEquality,
  'no-magic-env-strings': noMagicEnvStrings,
  'no-manual-retry-loop': noManualRetryLoop,
  'no-nested-try-catch': noNestedTryCatch,
  'no-optional-props': noOptionalProps,
  'no-react-query-missing': noReactQueryMissing,
  'no-relative-paths': noRelativePaths,
  'no-require-statements': noRequireStatements,
  'no-response-json-lowercase': noResponseJsonLowercase,
  'no-safeareaview': noSafeAreaView,
  'no-server-import-in-client': noServerImportInClient,
  'no-silent-skip': noSilentSkip,
  'no-string-coerce-error': noStringCoerceError,
  'no-stylesheet-create': noStylesheetCreate,
  'no-sync-fs': noSyncFs,
  'no-tab-bar-height': noTabBarHeight,
  'no-tailwind-animation-classes': noTailwindAnimationClasses,
  'no-type-assertion': noTypeAssertion,
  'prefer-guard-clauses': preferGuardClauses,
  'prefer-lucide-icons': preferLucideIcons,
  'prefer-named-params': preferNamedParams,
  'require-use-client': requireUseClient,
  'safe-json-parse': safeJsonParse,
  'scrollview-horizontal-flexgrow': scrollviewHorizontalFlexgrow,
  'sql-no-nested-calls': sqlNoNestedCalls,
  'tabs-screen-options-header-shown': tabsScreenOptionsHeaderShown,
  'textinput-keyboard-avoiding': textInputKeyboardAvoiding,
  'transition-gesture-scrollview': transitionGestureScrollview,
  'transition-prefer-blank-stack': transitionPreferBlankStack,
  'transition-progress-range': transitionProgressRange,
  'transition-shared-tag-mismatch': transitionSharedTagMismatch,
  'transition-worklet-directive': transitionWorkletDirective,
  'url-params-must-encode': urlParamsMustEncode,
};

export const ruleMeta: Record<string, RuleMeta> = {
  'browser-api-in-useeffect': browserApiInUseEffectMeta,
  'catch-must-log-to-sentry': catchMustLogToSentryMeta,
  'expo-font-loaded-check': expoFontLoadedCheckMeta,
  'expo-image-import': expoImageImportMeta,
  'fetch-response-ok-check': fetchResponseOkCheckMeta,
  'glass-interactive-prop': glassInteractivePropMeta,
  'glass-needs-fallback': glassNeedsFallbackMeta,
  'glass-no-opacity-animation': glassNoOpacityAnimationMeta,
  'header-shown-false': headerShownFalseMeta,
  'logger-error-with-err': loggerErrorWithErrMeta,
  'native-tabs-bottom-padding': nativeTabsBottomPaddingMeta,
  'no-border-width-on-glass': noBorderWidthOnGlassMeta,
  'no-class-components': noClassComponentsMeta,
  'no-complex-jsx-expressions': noComplexJsxExpressionsMeta,
  'no-emoji-icons': noEmojiIconsMeta,
  'no-inline-script-code': noInlineScriptCodeMeta,
  'no-inline-styles': noInlineStylesMeta,
  'no-loose-equality': noLooseEqualityMeta,
  'no-magic-env-strings': noMagicEnvStringsMeta,
  'no-manual-retry-loop': noManualRetryLoopMeta,
  'no-nested-try-catch': noNestedTryCatchMeta,
  'no-optional-props': noOptionalPropsMeta,
  'no-react-query-missing': noReactQueryMissingMeta,
  'no-relative-paths': noRelativePathsMeta,
  'no-require-statements': noRequireStatementsMeta,
  'no-response-json-lowercase': noResponseJsonLowercaseMeta,
  'no-safeareaview': noSafeAreaViewMeta,
  'no-server-import-in-client': noServerImportInClientMeta,
  'no-silent-skip': noSilentSkipMeta,
  'no-string-coerce-error': noStringCoerceErrorMeta,
  'no-stylesheet-create': noStylesheetCreateMeta,
  'no-sync-fs': noSyncFsMeta,
  'no-tab-bar-height': noTabBarHeightMeta,
  'no-tailwind-animation-classes': noTailwindAnimationClassesMeta,
  'no-type-assertion': noTypeAssertionMeta,
  'prefer-guard-clauses': preferGuardClausesMeta,
  'prefer-lucide-icons': preferLucideIconsMeta,
  'prefer-named-params': preferNamedParamsMeta,
  'require-use-client': requireUseClientMeta,
  'safe-json-parse': safeJsonParseMeta,
  'scrollview-horizontal-flexgrow': scrollviewHorizontalFlexgrowMeta,
  'sql-no-nested-calls': sqlNoNestedCallsMeta,
  'tabs-screen-options-header-shown': tabsScreenOptionsHeaderShownMeta,
  'textinput-keyboard-avoiding': textInputKeyboardAvoidingMeta,
  'transition-gesture-scrollview': transitionGestureScrollviewMeta,
  'transition-prefer-blank-stack': transitionPreferBlankStackMeta,
  'transition-progress-range': transitionProgressRangeMeta,
  'transition-shared-tag-mismatch': transitionSharedTagMismatchMeta,
  'transition-worklet-directive': transitionWorkletDirectiveMeta,
  'url-params-must-encode': urlParamsMustEncodeMeta,
};
