#!/usr/bin/env node
/**
 * Regenerate the rule registry (src/rules/index.ts) and the README rule
 * tables from the per-rule `meta` exports.
 *
 * Run after adding, removing, or renaming a rule. CI verifies this script
 * has been run and committed (no diff after running).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');
const RULES_DIR = join(ROOT, 'src', 'rules');
const INDEX_PATH = join(RULES_DIR, 'index.ts');
const README_PATH = join(ROOT, 'README.md');

interface DiscoveredRule {
  file: string;
  exportName: string;
  metaName: string;
  meta: {
    name: string;
    severity: 'error' | 'warning';
    platforms: string[] | null;
    category: string;
    description: string;
  };
}

const SKIP = new Set(['index.ts', 'meta.ts']);
const fileNames = readdirSync(RULES_DIR)
  .filter((f) => f.endsWith('.ts') && !SKIP.has(f))
  .sort();

const discovered: DiscoveredRule[] = [];
for (const file of fileNames) {
  const src = readFileSync(join(RULES_DIR, file), 'utf8');
  const nameM = src.match(/const RULE_NAME = '([^']+)';/);
  const exportM = src.match(/export function (\w+)\(/);
  const metaM = src.match(/export const meta = (\{[\s\S]*?\n\});/m);
  if (!nameM || !exportM || !metaM) {
    throw new Error(
      `${file}: missing RULE_NAME, export function, or export const meta block`,
    );
  }
  // Strip TS-only annotations so the literal is plain JS, then evaluate.
  // Object literals support unquoted keys, single quotes, and trailing
  // commas — all valid JS, so we wrap in `(...)` and Function-eval it.
  const cleaned = metaM[1]
    .replace(/\s+as\s+Platform\[\]\s*\|\s*null/g, '')
    .replace(/\s+as\s+const\b/g, '');
  let parsed: DiscoveredRule['meta'];
  try {
    parsed = new Function(`return (${cleaned});`)();
  } catch (err) {
    throw new Error(`${file}: failed to parse meta block: ${(err as Error).message}\n${cleaned}`);
  }
  discovered.push({
    file,
    exportName: exportM[1],
    metaName: exportM[1] + 'Meta',
    meta: parsed,
  });
}

discovered.sort((a, b) => a.meta.name.localeCompare(b.meta.name));

// Generate src/rules/index.ts
const imports = discovered
  .map((d) => `import { ${d.exportName}, meta as ${d.metaName} } from './${d.file.replace(/\.ts$/, '')}';`)
  .join('\n');
const rulesObj = discovered
  .map((d) => `  '${d.meta.name}': ${d.exportName},`)
  .join('\n');
const metaObj = discovered
  .map((d) => `  '${d.meta.name}': ${d.metaName},`)
  .join('\n');
const indexTs = `// AUTO-GENERATED by scripts/sync.ts — do not edit manually.
// Run \`npm run sync\` after adding or removing a rule.
import type { RuleFunction, RuleMeta } from '../types';
${imports}

export const rules: Record<string, RuleFunction> = {
${rulesObj}
};

export const ruleMeta: Record<string, RuleMeta> = {
${metaObj}
};
`;
writeFileSync(INDEX_PATH, indexTs);

// Generate README rule section between markers
const DISPLAY_ORDER = [
  ['Expo Router', 'Expo Router Rules', true],
  ['React Native / Expo', 'React Native / Expo Rules', true],
  ['Liquid Glass', 'Liquid Glass Rules (expo-glass-effect)', true],
  ['Next.js', 'Next.js Rules', true],
  ['React / JSX', 'React / JSX Rules', true],
  ['Screen Transitions', 'Screen Transitions Rules (react-native-screen-transitions)', true],
  ['Tailwind CSS', 'Tailwind CSS Rules', true],
  ['Backend / SQL', 'Backend / SQL Rules', true],
  ['URL', 'URL Rules', false],
  ['Error Handling', 'Error Handling Rules', false],
  ['Code Style', 'Code Style Rules', true],
  ['General', 'General Rules', true],
] as const;

const grouped = new Map<string, DiscoveredRule[]>();
for (const d of discovered) {
  const arr = grouped.get(d.meta.category) ?? [];
  arr.push(d);
  grouped.set(d.meta.category, arr);
}
// Escape characters that have meaning inside a Markdown table cell.
function mdCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\*/g, '\\*');
}

const sectionLines: string[] = [];
for (const [cat, title, withPlatform] of DISPLAY_ORDER) {
  const items = grouped.get(cat);
  if (!items?.length) continue;
  sectionLines.push(`### ${title}`);
  sectionLines.push('');
  if (withPlatform) {
    sectionLines.push('| Rule | Severity | Platform | Description |');
    sectionLines.push('| --- | --- | --- | --- |');
    for (const d of items.sort((a, b) => a.meta.name.localeCompare(b.meta.name))) {
      const plat = d.meta.platforms?.join(', ') ?? 'universal';
      sectionLines.push(`| \`${d.meta.name}\` | ${d.meta.severity} | ${plat} | ${mdCell(d.meta.description)} |`);
    }
  } else {
    sectionLines.push('| Rule | Severity | Description |');
    sectionLines.push('| --- | --- | --- |');
    for (const d of items.sort((a, b) => a.meta.name.localeCompare(b.meta.name))) {
      sectionLines.push(`| \`${d.meta.name}\` | ${d.meta.severity} | ${mdCell(d.meta.description)} |`);
    }
  }
  sectionLines.push('');
}

const readme = readFileSync(README_PATH, 'utf8');
const startMarker = '<!-- AUTOGEN:RULES — managed by scripts/sync.ts; run `npm run sync` to update. -->';
const endMarker = '<!-- /AUTOGEN:RULES -->';
const startIdx = readme.indexOf(startMarker);
const endIdx = readme.indexOf(endMarker);
if (startIdx < 0 || endIdx < 0) {
  throw new Error('README.md is missing AUTOGEN:RULES markers');
}
// Update count in the heading just above the markers
const countRe = /## Available Rules \((\d+) total\)/;
const newCount = `## Available Rules (${discovered.length} total)`;
const updatedReadme =
  readme.slice(0, startIdx + startMarker.length) +
  '\n\n' +
  sectionLines.join('\n').trimEnd() +
  '\n\n' +
  readme.slice(endIdx);
writeFileSync(README_PATH, updatedReadme.replace(countRe, newCount));

console.log(`sync: ${discovered.length} rules — wrote src/rules/index.ts + README.md`);
